// Define the number of questions you want to appear in the quiz
		const numQuestionsToShow = 30; // Change this number as desired

		// Define the questions, answers, and feedback
		const questions = [
		  
"<h2>Quan es converteix un element HTML en un grid container?</h2>",
"<h2>Quina propietat pots utilitzar per canviar la mida d'un gap?</h2>",
"<h2>Si tens mÃ©s de quatre Ã­tems en quatre columnes de grid, el grid automÃ ticament...</h2>",
"<h2>La propietat grid-row defineix</h2>",
"<h2>Quina propietat especifÃ­ca la posiciÃ³ d'una imatge?</h2>",
"<h2>En CSS com indiques el final d'un margin en la direcciÃ³ d'el block?</h2>",
"<h2>Quina propietat especifÃ­ca la width d'una taula?</h2>",
"<h2>Que fa la funciÃ³ attr().?</h2>",
"<h2>Quin model de colors no Ã©s una funciÃ³ en CSS?</h2>",
"<h2>Quina de les seguents propietats s'utilitza per definir el nÃºmero de columnes?</h2>",
"<h2>Quina d'aquestes propietats s'utlitza per establir l'espai entre rows i columns?</h2>",
"<h2>Quina d'aquestes propietats indica que un element grid ha d'ocupar el mÃ xim espai?</h2>",
"<h2>Quina propietat CSS grid s'utilitza per definir les Ã rees d'un grid i assignar-li elements?</h2>",
"<h2>De les seguents opcions, quina Ã©s un selector d'atribut CSS?</h2>",
"<h2>Quin dels seguents selectors CSS serveix per seleccionar tots els elements directes d'un pare?</h2>",
"<h2>Quina d'aquestes propietats Ã©s animable utilitzant transicions?</h2>",
"<h2>Quina funciÃ³ CSS es pot utilitzar per crear una animaciÃ³ personalitzada?</h2>",
"<h2>Quina propietat CSS s'utilitza per definir la duraciÃ³ d'una animaciÃ³?</h2>",
"<h2>Quants colors suporten els navegador actuals?</h2>",
"<h2>Quina unitat CSS representa una fracciÃ³ d'espai disponible en un flex container?</h2>",
"<h2>Quina unitat CSS s'utilitza tÃ­picament per mesurar l'alÃ§ada de lÃ­nies de text i marges?</h2>",
"<h2>Quina unitat CSS s'utilitza en relatiu a la amplada de 0?</h2>",
"<h2>Quin Ã©s el valor per defecte de la propietat CSS text-area</h2>",
"<h2>Quin Ã©s el valor per defecte de la propietat CSS article</h2>",
"<h2>Quina propietat CSS s'utilitza per afegir o canviar les icones dins dels botons?</h2>",
"<h2>QuÃ¨ representa el selector :hover en CSS?</h2>",
"<h2>Quina Ã©s la funciÃ³ de la propietat CSS url().?</h2>",
"<h2>Quina funciÃ³ duu a terme el selector :valid?</h2>",
"<h2>La propietat align-content serveix per:</h2>",
"<h2>Quin navegador suporta menys les propietats grid?</h2>",
];

const answers = [
		["A. Quan display: grid; ", "B. Quan <div display-grid>  ", "C. Quan grid-contner = display ", "D. Quan <div class=grid-display> "],
		["A. column-size ", "B. column=gap ", "C. column-gap ", "D. grid-size "],
		["A. AfegirÃ  una nova row", "B. AfegirÃ  una nova columna ", "C. AfegirÃ  una columna i un row ", "D. CrearÃ  un nou grid "],
		["A. Com de gran serÃ  la row", "B. En quina row posarÃ  un Ã­tem ", "C. On comenÃ§arÃ  la row", "D. Quins Ã­tems poden estar en la row"],
		["A. background:position", "B. background:position", "C. background-origin ", "D. background-place"],
		["A. margin-end", "B. margin-inline-end", "C. margin-block-bottom ", "D. margin-block-end"],
		["A. tab-size", "B. tab-width", "C. tab-big", "D. tab-weight"],
		["A. Crida a un atribut per quÃ¨ faci una funciÃ³", "B. Fa que funcioni un atribut correctament", "C. Retorna el valor d'un atribut a un element seleccionat", "D. Indica el comenÃ§ament d'un atribut nou "],
		["A. RGB", "B. RGBA", "C. HSL", "D. CMYK"],
		["A. grid-columns", "B. grid-template-columns", "C. column-count", "D. grid-column"],
		["A. grid-gap", "B. grid-space", "C. grid-margin", "D. grid-padding"],
		["A. grid-expand", "B. grid-fill", "C. grid-auto-flow", "D. grid-cell"],
		["A. grid-rows", "B. grid-areas", "C. grid-template", "D. grid-columns"],
		["A. :hover", "B. [atribute=value]", "C. [attr=val]", "D. .class"],
		["A. +", "B. >", "C. ~", "D. *"],
		["A. display", "B. font-family", "C. position", "D. background-color"],
		["A. animate()", "B. keyframes", "C. transform()", "D. transition()"],
		["A. animation-duration", "B. animation-delay", "C. animation-timing", "D. animation-count"],
		["A. 138", "B. 139", "C. 140", "D. 141"],
		["A. px", "B. em", "C. %", "D. fr"],
		["A. rem", "B. ch", "C. mm", "D. vw"],
		["A. px", "B. ch", "C. ex", "D. em"],
		["A. justify", "B. underline", "C. none", "D. center"],
		["A. display:none;", "B. display:block", "C. display:all;", "D. display:default;"],
		["A. content", "B. icon", "C. background-image", "D. image-source"],
		["A.  L'Ãºltim child d'un element", "B. Un element que estÃ  sent arrossegat", "C.   Un element amb un estil alternatiu.", "D.  Un element quan el cursor del ratolÃ­ estÃ  sobre ell"],
		["A. Canviar el color de fons d'un element", "B. EnllaÃ§ar un fitxer d'estil CSS extern", "C. Establir la mida d'una imatge", "D. Fer una animaciÃ³ CSS"],
		["A. Selecciona els elements amb valors vÃ lids", "B. Determina si un element Ã©s vÃ lid", "C. NomÃ©s entra a webs validades", "D. Valida que el codi estigui ben escrit"],
		["A. Alinear al centre els elements", "B. Alinear verticalment el grid al container", "C. Alinear amb la pÃ gina el grid", "D. Alinear amb el container el tÃ­tol"],
		["A. Opera", "B. Firefox", "C. Chrome", "D. Safari"],
		
		];
		
const feedback = [
  "AixÃƒÂ­ ÃƒÂ©s! Un element HTML es converteix en grid fent la funciÃ³ display: grid; .",
  "Correcte! Amb la propietat column-gap pots modificar la mida del gap. ",
  "Correcte! Si es dona aquest cas el grid afegirÃ  una nova row per introduÃ¯r els nou Ã­tems.",
  "Correcte! DefinirÃ  en quina row ha de colÂ·locar el Ã­tem.",
  "AixÃƒÂ­ ÃƒÂ©s! La propietat background-position indica la posiciÃ³ de la imatge.",
  "Correcte! Amb margin-block-end indiques el final d'un margin en direcciÃ³ del block.",
  "AixÃƒÂ­ ÃƒÂ©s! La propietat tab-size serveix per modificar la width d'una taula.",
  "Correcte! La funciÃ³ attr() serveix peer retornar un atribut a l'element que volguem.",
  "Correcte! El model CMYK no Ã©s una funciÃ³.",
  "Correcte! Ã‰s la propietat grid-template-column la que s'utiltza per definir columnes.",
  "AixÃƒÂ­ ÃƒÂ©s! La propietat grid-gap estableix l'espai entre rows i columns.",
  "AixÃƒÂ­ ÃƒÂ©s! Ho indica la propietat grid-auto-flow.",
  "AixÃƒÂ­ ÃƒÂ©s! S'utilitza la funciÃ³ grid-areas per fer-ho.",
  "Correcte! Ã‰s [attribute=value] la que ho selecciona.",
  "Correcte! Aquest Ã©s el selector que ho fa >.",
  "Correcte! L'Ãºnica animable Ã©s background-color.",
  "Correcte! En aquest cas Ã©s la propietat transform la que serveix.",
  "Correcte! Animation-duration serveix per indicar quant dura una animaciÃ³.",
  "Correcte! Els navegadors actuals suporten 140 colors.",
  "Correcte! El espai disponible d'un flex container Ã©s en fr.",
  "Correcte! Les lÃ­nies de text i marges es mesuren en rem.",
  "Correcte! Per mesurar l'amplada de 0 es mesura en ch.",
  "Correcte! Ã‰s none el seu valor predeterminat.",
  "Correcte! Ã‰s display:block; el seu valor predeterminat.",
  "Correcte! La funciÃ³ background-image Ã©s la que canvia les icones.",
  "Correcte! Ã‰s un element quan passa el cursor del ratolÃ­ per sobre.",
  "Correcte! Serveix per enllaÃ§ar un fitxer CSS extern.",
  "Correcte! El selector :valid serveix per seleccionar els elements amb valors vÃ lids.",
  "Correcte! Align-content serveix per alinear verticalment el grid dins el container",
  "Correcte! Safari Ã©s el navegador que menys suporta les propietats de grid.",
  ];
  
  const correctAnswers = [
			"A", "C", "A", "B", "B", "D", "A", "C", "D", "B", "A", "C", "B", "B", "B", "D", "C", "A", "C", "D", "A", "B", "C", "B", "C", "D", "B", "A", "B", "D"
			
			];
